### ISSUE TITLE
Guest unable to view Bookmarks

### ISSUE THREAD

**Issue by Felli** [staxDB/humhub-modules-bookmark#11]
At the moment `isGuest` doesn't have the ability to view content that's bookmarked by a user, even if there is an option for `isGuest` to actually view it, this should either be fixed or removed completely. :thinking:

```text
yii\base\ErrorException: Trying to get property 'id' of non-object in /home/USER/public_html/SITE/protected/modules/bookmark/components/ProfileBookmarkStream.php:83 Stack trace:
```

**Comment by Felli** [comment]
Just an update this is fixed with #10. :wink:

**Comment by Ace2213** [comment]
I have tested to make sure that bookmarks are per-user and not global. But I do find it odd that the bookmark button is visible at all to guests, and shows an access error if you try to access it. Wouldn't it be better if this button was hidden completely for guests? I'd do it myself if I knew how.

RIP Felli.

**Comment by staxDB** [comment]
Merged your pr
